epoch : 100
lr : 0.003
lr_gamma : 0.5
lr_step_size : 20
weight_decay : 0.001

using_temporal_graph : False
using_knn_graph : False

loss_weight_alpha : 1

data:
  split_ratio : 0.8
  time_dummy_duration : 480
  temporal_graph :
    using_cache : True
    time_interval : 45
    weighted_edge : True
    self_weight : 12

  knn_graph :
    using_cache : True
    k : 600
    weighted_edge : True
    self_weight : 1

models:
  std_gcn_temporal:
    enable : False
    layer_dim : 512
    layer_num : 4
    dropout : 0.1

  gcn_temporal:
    enable : False
    layer_dim : [512, 512, 1]
    dropout : 0.1

  mlp:
    enable : False
    layer_dim : [128, 64]
    dropout : 0.1

  random_forest:
    enable : False
    n_estimators : 1000
    min_samples_split : 200
    max_features : 'sqrt'
    criterion : 'gini'

  balanced_random_forest:
    enable : False
    n_estimators : 500
    min_samples_split : 2
    max_features : 'sqrt'
    criterion : 'gini'