epoch : 100
lr : 0.01
lr_gamma : 0.83
lr_step_size : 10
weight_decay : 0.001

using_temporal_graph : True
using_knn_graph : True

loss_weight_alpha : 0.95

data:
  split_ratio : 0.8
  time_dummy_duration : 60
  temporal_graph :
    using_cache : True
    time_interval : 60
    weighted_edge : True
    self_weight : 1

  knn_graph :
    using_cache : True
    k : 60
    weighted_edge : True
    self_weight : 1

models:
  gcn:
    enable : False
    output_dim : [1024, 256, 1]
    dropout : 0.1

  mlp:
    enable : True
    output_dim : [1024, 256, 1]
    dropout : 0.1