epoch : 250
lr : 0.003
lr_gamma : 0.5
lr_step_size : 50
weight_decay : 0.001

using_temporal_graph : True
using_knn_graph : True

loss_weight_alpha : 1

data:
  split_ratio : 0.8
  time_dummy_duration : 480
  temporal_graph :
    using_cache : True
    time_interval : 90
    weighted_edge : True
    self_weight : 20

  knn_graph :
    using_cache : True
    k : 6
    weighted_edge : False
    self_weight : 32

models:
  gtn:
    enable : False
    layer_dim : [512, 1]
    heads : 8
    dropout : 0.3

  gcn_temporal:
    enable : False
    layer_dim : [512, 1]
    dropout : 0.4

  gcn_knn:
    enable : False
    layer_dim : [512, 512, 1]
    dropout : 0.4

  mlp:
    enable : False
    layer_dim : [256, 64]
    dropout : 0.1

  random_forest:
    enable : True
    n_estimators : 1000
    min_samples_split : 200
    max_features : 'sqrt'
    criterion : 'gini'

  random_forest_balanced:
    enable : True
    n_estimators : 1000
    min_samples_split : 200
    max_features : 'sqrt'
    criterion : 'gini'

  svm:
    enable: True
    sgd: False

  svm_balanced:
    enable: True
    sgd: False

  regression:
    enable: True
    sgd: False

  regression_balanced:
    enable: True
    sgd: False

  std_gcn:
    enable: False
    num_layer: 3
    hidden_size: 512
    dropout: 0.3