epoch : 120
lr : 0.3
lr_gamma : 0.5
lr_step_size : 20
weight_decay : 0.001

using_temporal_graph : True
using_knn_graph : True

loss_weight_alpha : 1

data:
  split_ratio : 0.8
  time_dummy_duration : 480
  temporal_graph :
    using_cache : True
    time_interval : 90
    weighted_edge : True
    self_weight : 32

  knn_graph :
    using_cache : True
    k : 6
    weighted_edge : False
    self_weight : 32

models:
  std_gcn_temporal:
    enable : False
    layer_dim : 512
    layer_num : 4
    dropout : 0.1

  gcn_temporal:
    enable : True
    layer_dim : [512, 512, 1]
    dropout : 0.4

  gcn_knn:
    enable : True
    layer_dim : [512, 512, 1]
    dropout : 0.4

  mlp:
    enable : True
    layer_dim : [256, 64]
    dropout : 0.1

  random_forest:
    enable : False
    n_estimators : 1000
    min_samples_split : 200
    max_features : 'sqrt'
    criterion : 'gini'

  balanced_random_forest:
    enable : False
    n_estimators : 1000
    min_samples_split : 200
    max_features : 'sqrt'
    criterion : 'gini'

  svm:
    enable: False

  regression:
    enable: False

  lstm:
    enable: False
    seq_len : 1
    num_layer: 1
    hidden_size: 128
    dropout: 0.3