epoch : 150
lr : 0.01
lr_gamma : 0.83
lr_step_size : 1
weight_decay : 0.001

using_temporal_graph : True
using_knn_graph : True

loss_weight_alpha : 1

data:
  split_ratio : 0.8
  time_dummy_duration : 60
  temporal_graph :
    using_cache : True
    time_interval : 60
    weighted_edge : True
    self_weight : 1

  knn_graph :
    using_cache : True
    k : 60
    weighted_edge : True
    self_weight : 1

models:
  gcn:
    enable : False
    output_dim : [1024, 256]
    dropout : 0.1

  mlp:
    enable : True
    hidden_dim : [256]
    dropout : 0.1